In [1]:
import numpy as np

In [2]:
x = [1,2,3,4]
y = [1] + x[:]
y[1] = 0
print(x,y)

[1, 2, 3, 4] [1, 0, 2, 3, 4]


In [3]:
y = [4,5,6]
for i, el in enumerate(y):
    print(i,el)

0 4
1 5
2 6


In [4]:
a = np.arange(16).reshape(4,4)
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [7]:
np.stack([a,a], axis=1).shape

(4, 2, 4)

In [9]:
for i in range(5)[::-1]:
    print(i)

4
3
2
1
0


In [10]:
a = [
]

In [16]:
a.insert(0, 3)

In [17]:
a

[3, 2]

In [18]:
a[-1]

2

In [19]:
a = np.arange(16).reshape(4,4)

In [20]:
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [24]:
np.where( a > 4.0 )

(array([1, 1, 1, 2, 2, 2, 2, 3, 3, 3, 3]),
 array([1, 2, 3, 0, 1, 2, 3, 0, 1, 2, 3]))

In [34]:
b, c = np.where( a == 4 )

In [35]:
b, c

(array([1]), array([0]))

In [36]:
for j in b:
    print(b[j])

IndexError: index 1 is out of bounds for axis 0 with size 1