In [1]:
import numpy as np

In [5]:
a = np.array([[1, 2], [3, 4]])
b = np.array([[5, 6], [7,8]])

In [6]:
a < 2

array([[ True, False],
       [False, False]])

In [7]:
b

array([[5, 6],
       [7, 8]])

In [8]:
b[a < 2] = 0

In [9]:
b

array([[0, 6],
       [7, 8]])

In [12]:
np.random.randn(5)

array([-5.45941767e-04, -4.71986823e-01,  9.24576072e-01,  1.16969867e+00,
       -1.06211132e-01])