In [2]:
import numpy as np

In [3]:
x =np.array([1,2,3,4])

In [4]:
import torch
import torchvision
import torchvision.transforms as T
import random
import numpy as np
from scipy.ndimage.filters import gaussian_filter1d
import matplotlib.pyplot as plt
from cs231n.image_utils import SQUEEZENET_MEAN, SQUEEZENET_STD
from PIL import Image

In [5]:
loss = torch.nn.CrossEntropyLoss()
input = torch.randn(3, 5, requires_grad=True)
print(input)
target = torch.empty(3, dtype=torch.long).random_(5)
print(target)
output = loss(input, target)
print(output)
x = output.backward()
print(input.grad)

tensor([[ 0.0433, -1.7715,  0.4328, -0.3040,  0.8745],
        [-0.7561, -0.1997, -1.3543, -1.5759, -0.0858],
        [ 1.1748,  0.0672, -1.0566, -1.7347,  0.9715]], requires_grad=True)
tensor([2, 1, 3])
tensor(2.0896, grad_fn=<NllLossBackward>)
tensor([[ 0.0591,  0.0096, -0.2461,  0.0417,  0.1357],
        [ 0.0586, -0.2311,  0.0322,  0.0258,  0.1145],
        [ 0.1444,  0.0477,  0.0155, -0.3255,  0.1178]])


In [6]:
np.linalg.norm(input.grad)

0.5469542

In [7]:
a = torch.randn(4, 4)

In [8]:
a

tensor([[ 0.0303, -0.5344, -0.6318,  0.3458],
        [ 1.1014, -0.5569,  2.1155,  0.0129],
        [ 0.2096, -0.3429, -2.4642, -0.1351],
        [-0.1319,  0.9020, -0.1552, -0.7375]])

In [9]:
torch.max(a,0)

torch.return_types.max(
values=tensor([1.1014, 0.9020, 2.1155, 0.3458]),
indices=tensor([1, 3, 1, 0]))

In [10]:
x, _ = torch.max(a,0)
print(x)

tensor([1.1014, 0.9020, 2.1155, 0.3458])


In [11]:
a

tensor([[ 0.0303, -0.5344, -0.6318,  0.3458],
        [ 1.1014, -0.5569,  2.1155,  0.0129],
        [ 0.2096, -0.3429, -2.4642, -0.1351],
        [-0.1319,  0.9020, -0.1552, -0.7375]])

In [12]:
torch.tensor([5])

tensor([5])

In [13]:
np.linalg.norm(x)

2.5732446

In [14]:
b = np.array([1,2,3,4,5,6])

In [15]:
b[-2:]

array([5, 6])

In [16]:
img = torch.randn(1, 3, 224, 224).mul_(1000)

In [17]:
img

tensor([[[[ -729.9498,   324.5400,  -422.4324,  ..., -1569.2019,
            -697.6097,  1729.2593],
          [ -948.2082, -1089.4308,  -800.7894,  ...,  -586.3788,
           -1025.9258,  -248.7389],
          [ -486.6609,    83.6247,  -746.1255,  ...,  -199.0134,
           -2275.7571,   402.5091],
          ...,
          [  631.3796,   592.9535, -1904.6392,  ...,    63.9675,
             471.3653,   465.0879],
          [  450.1900, -2271.2107,   894.0163,  ...,   823.7426,
             -70.9699,    49.8105],
          [ -139.8431,   244.1976, -1410.6860,  ...,  -615.2522,
             942.7972,   545.6707]],

         [[ 1165.3934,   867.1899,  -762.6273,  ...,  -250.2987,
            1052.1863,  1419.3502],
          [ -909.8073,  1493.9304, -1129.1180,  ...,  1015.7662,
            2010.7599,    71.4666],
          [-1177.5419,  -956.0621, -1386.2814,  ...,   452.4653,
            1441.1124, -1557.0684],
          ...,
          [ -764.8566,  -849.8227,  1787.9196,  ...,  1812.

In [18]:
a = torch.tensor([[1,2,3,4,5], [1,2,3,4,5]])
a

tensor([[1, 2, 3, 4, 5],
        [1, 2, 3, 4, 5]])

In [19]:
np.linalg.norm(a)

10.488088481701515

In [20]:
b = torch.tensor([1,2,3,4,5])

In [21]:
b * b

tensor([ 1,  4,  9, 16, 25])

In [22]:
torch.sqrt(torch.sum(b*b))

RuntimeError: sqrt_vml_cpu not implemented for 'Long'

In [ ]:
b ^ 2

In [ ]:
b

In [ ]:
torch.pow(torch.sum(b*b),.5)

In [ ]:
np.sqrt(torch.sum(b*b))

In [ ]:
np.linalg.norm(b)

In [ ]:
b

In [ ]:
c = b.view(2,-1)

In [23]:
x = torch.arange(6)

x.view(3, -1)

tensor([[0, 1],
        [2, 3],
        [4, 5]])

In [24]:
b = torch.tensor([1,2])
import numpy as np

In [25]:
b.tolist()

[1, 2]

In [26]:
c = torch.tensor([1,2,3,4,5,6,7,8])

In [27]:
c[1:]

tensor([2, 3, 4, 5, 6, 7, 8])

In [28]:
x= np.arange(16)

In [29]:
x

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [30]:
x[4:8]

array([4, 5, 6, 7])

In [31]:
a1 = np.arange(16).reshape(4,4)
a2 = np.arange(16).reshape(4,4)
a1.shape

(4, 4)

In [32]:
a1, a2

(array([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11],
        [12, 13, 14, 15]]), array([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11],
        [12, 13, 14, 15]]))

In [33]:
np.concatenate([a1,a2], axis=1).shape

(4, 8)

In [34]:
np.sum(a1, axis=1)

array([ 6, 22, 38, 54])

In [35]:
x = [1,2,3]

In [36]:
x[-1]

3

In [37]:
x

[1, 2, 3]

In [47]:
x = np.array([1,2,3])

In [48]:
x = 1 *(x>1.5)

In [49]:
x

array([0, 1, 1])